AWSTemplateFormatVersion: '2010-09-09'
Description: A sample template

Parameters:
  GitHubBranchName:
    Description: GitHub branch name
    Type: String
    Default: master
  GitHubRepo:
    Description: GitHub repo URL
    Type: String
  GitHubWebhookSecret:
    Type: String
    NoEcho: true
  GitHubUsername:
    Type: String
    NoEcho: true
  GitHubOAuthToken:
    Type: String
    NoEcho: true
  ArtifactStoreS3Location:
    Type: String
    Description: Name of the S3 bucket to store CodePipeline artifacts
    Default: none
  CreateArtifactStore:
    Type: String
    Description: set to yes to create S3 bucket
    Default: "no"
    AllowedValues:
      - "yes"
      - "no"
    ConstraintDescription: must be yes or no
  CreateECRRepository:
    Type: String
    Description: set to yes to create ECR Repository
    Default: "no"
    AllowedValues:
      - "yes"
      - "no"
    ConstraintDescription: must be yes or no

Conditions:
  CreateArtifactStoreCondition: !Equals [ !Ref CreateArtifactStore, "yes" ]
  CreateECRRepositoryCondition: !Equals [ !Ref CreateECRRepository, "yes" ]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArtifactStoreS3Location
    Condition: CreateArtifactStoreCondition

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "contentacms"
    Condition: CreateECRRepositoryCondition

  CodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: CodePipelineRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        -
          PolicyName: "CodePipelinePolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action: iam:PassRole
                Resource: "*"
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - cloudformation.amazonaws.com
                      - elasticbeanstalk.amazonaws.com
                      - ec2.amazonaws.com
                      - ecs-tasks.amazonaws.com
                      - codebuild.amazonaws.com
              -
                Effect: Allow
                Action:
                  - opsworks:DescribeStacks
                  - devicefarm:GetRun
                  - rds:*
                  - cloudformation:CreateChangeSet
                  - autoscaling:*
                  - codebuild:BatchGetBuilds
                  - devicefarm:ScheduleRun
                  - servicecatalog:ListProvisioningArtifacts
                  - devicefarm:ListDevicePools
                  - cloudformation:UpdateStack
                  - servicecatalog:DescribeProvisioningArtifact
                  - cloudformation:DescribeChangeSet
                  - devicefarm:ListProjects
                  - cloudformation:ExecuteChangeSet
                  - sns:*
                  - lambda:ListFunctions
                  - codedeploy:RegisterApplicationRevision
                  - lambda:InvokeFunction
                  - opsworks:DescribeDeployments
                  - devicefarm:CreateUpload
                  - cloudformation:*
                  - cloudformation:DescribeStacks
                  - codecommit:GetUploadArchiveStatus
                  - cloudwatch:*
                  - opsworks:DescribeInstances
                  - cloudformation:DeleteStack
                  - ecr:DescribeImages
                  - ecs:*
                  - ec2:*
                  - codebuild:StartBuild
                  - opsworks:DescribeApps
                  - opsworks:UpdateStack
                  - cloudformation:ValidateTemplate
                  - codedeploy:CreateDeployment
                  - codedeploy:GetApplicationRevision
                  - codedeploy:GetDeploymentConfig
                  - sqs:*
                  - servicecatalog:CreateProvisioningArtifact
                  - cloudformation:DeleteChangeSet
                  - codecommit:GetCommit
                  - servicecatalog:DeleteProvisioningArtifact
                  - codedeploy:GetApplication
                  - cloudformation:SetStackPolicy
                  - codecommit:UploadArchive
                  - s3:*
                  - elasticloadbalancing:*
                  - codecommit:CancelUploadArchive
                  - devicefarm:GetUpload
                  - elasticbeanstalk:*
                  - opsworks:UpdateApp
                  - opsworks:CreateDeployment
                  - cloudformation:CreateStack
                  - codecommit:GetBranch
                  - servicecatalog:UpdateProduct
                  - codedeploy:GetDeployment
                  - opsworks:DescribeCommands
                Resource: "*"

  CloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: CloudFormationRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        -
          PolicyName: "CodePipelineInvokedCFNPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "iam:*"
                  - "lambda:*"
                  - "s3:*"
                  - "apigateway:*"
                  - "ssm:Describe*"
                  - "ssm:Get*"
                  - "ssm:List*"
                  - "cloudfront:*"
                  - "cognito-identity:*"
                  - "cognito-idp:DescribeUserPoolDomain"
                  - "cognito-idp:CreateUserPool"
                  - "cognito-sync:QueryRecords"
                  - "cognito-idp:ListUserPools"
                  - "cognito-sync:*"
                  - "cognito-idp:*"
                  - "cloudformation:*"
                Resource:
                  - "*"

  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: CodeBuildRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /service-role/
      Policies:
        -
          PolicyName: "CodeBuildNestedCFNAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "ec2:DescribeAccountAttributes"
                  - "ec2:DescribeVpcs"
                  - "ec2:DescribeRouteTables"
                  - "ec2:DescribeInternetGateways"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeAddresses"
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeKeyPairs"
                  - "ec2:DescribeAvailabilityZones"
                  - "ec2:DescribeSecurityGroups"
                  - "cloudformation:ValidateTemplate"
                  - "iam:GetRole"
                  - "iam:GetRolePolicy"
                  - "logs:CreateLogStream"
                  - "logs:CreateLogGroup"
                  - "logs:PutLogEvents"
                  - "ecr:DescribeImageScanFindings"
                  - "ecr:GetLifecyclePolicyPreview"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:GetAuthorizationToken"
                  - "ecr:ListTagsForResource"
                  - "ecr:UploadLayerPart"
                  - "ecr:PutImage"
                  - "ecr:BatchGetImage"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:DescribeImages"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetRepositoryPolicy"
                  - "ecr:GetLifecyclePolicy"
#                  - "ssm:GetParameters"
#                  - "ssm:GetParameter"
                Resource:
                  - "*"
              -
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:ListBucket"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                Resource:
                  - Fn::Sub: arn:aws:s3:::codepipeline-${AWS::Region}-*
                  - Fn::Sub: arn:aws:s3:::${ArtifactStoreS3Location}/*
                  - Fn::Sub: arn:aws:s3:::${ArtifactStoreS3Location}
#              -
#                Effect: "Allow"
#                Action:
#                  - "s3:PutObject"
#                  - "s3:PutObjectRetention"
#                  - "s3:PutObjectVersionAcl"
#                  - "s3:PutObjectVersionTagging"
#                  - "s3:PutObjectTagging"
#                  - "s3:PutObjectAcl"
#                Resource:
#                  - "arn:aws:s3:::{{resolve:ssm:LEDSTRIP_URL:1}}/*"

  DeployPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name:
        Fn::Sub: CodePipeline-${AWS::StackName}
      RoleArn:
        Fn::GetAtt: [ CodePipelineRole, Arn ]
      Stages:
        -
          Name: GitHubSource
          Actions:
            - Name: FetchFromGithub
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: "1"
                Provider: GitHub
              OutputArtifacts:
                -
                  Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubUsername
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranchName
                OAuthToken: !Ref GitHubOAuthToken
                PollForSourceChanges: false
              RunOrder: 1
        -
          Name: BuildContainerImage
          Actions:
            -
              Name: BuildContainerImage
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                -
                  Name: BuildOutput
              Configuration:
                ProjectName: !Ref BuildContainerImage
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location:
          Ref: ArtifactStoreS3Location

  AppPipelineWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubWebhookSecret
      Filters:
        - JsonPath: $.ref
          MatchEquals: 'refs/heads/{Branch}'
      TargetPipeline: !Ref DeployPipeline
      TargetAction: FetchFromGithub
      Name: !Sub 'PipelineWebhook-${AWS::StackName}'
      TargetPipelineVersion: !GetAtt
        - DeployPipeline
        - Version
      RegisterWithThirdParty: true

  BuildContainerImage:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Sub: BuildLambda-${AWS::StackName}
      Description: BuildContainerImage
      ServiceRole: !Sub '${CodeBuildRole.Arn}'
      Artifacts:
        Type: CODEPIPELINE
        Location: !Ref ArtifactStoreS3Location
        Name: !Sub 'BuildContainerImage-${AWS::StackName}'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: True
        EnvironmentVariables:
          -
            Name: S3_BUCKET
            Type: PLAINTEXT
            Value: !Ref ArtifactStoreS3Location
          -
            Name: IMAGE_REPO_NAME
            Type: PLAINTEXT
            Value: !Ref Repository
          -
            Name: IMAGE_TAG
            Type: PLAINTEXT
            Value: latest
          -
            Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref "AWS::AccountId"
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Source:
        BuildSpec: !Sub |
          version: 0.2
          phases:
            pre_build:
              commands:
                - echo Logging in to Amazon ECR...
                - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            build:
              commands:
                - echo Build started on `date`
                - echo Building the Docker image...
                - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
                - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
            post_build:
              commands:
                - echo Build completed on `date`
                - echo Pushing the Docker image...
                - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        Type: CODEPIPELINE
      TimeoutInMinutes: 60




#  ECS Cluster
#  ECS Task Definition
#  ECS Service
